---
- hosts: all
  become: True
  tasks:
    - copy:
      content: "Hello world"
      dest: /tmp/abc.txt

  handlers:
    - name: Restart apache
      service:
        name: httpd
        state: restart
        enabled: yes
...      
